#!/bin/sh

git checkout github
git reset --hard main

git config commit.gpgsign false

git filter-branch --force --msg-filter \
    'sed "/iQIcBA.*/,/.*END PGP SIGNATURE.*/d"' -- github

git filter-branch --force --index-filter \
    'git rm --cached --ignore-unmatch ssh_config known_hosts' --prune-empty -- github

git config commit.gpgsign true

